### ISSUE TITLE
Don't compile in Linux Kernel 4.8.0

### ISSUE THREAD

**Issue by dcialdella** [neurobin/MT7630E#40]
make -C /lib/modules/`uname -r`/build M=/opt/MT7630E-release/rt2x00 modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-040800rc3-generic'
  CC [M]  /opt/MT7630E-release/rt2x00/rt2x00dev.o
In file included from /opt/MT7630E-release/rt2x00/rt2x00dev.c:32:0:
/opt/MT7630E-release/rt2x00/rt2x00.h:2166:40: error: ‘IEEE80211_NUM_BANDS’ undeclared here (not in a function)
  struct ieee80211_supported_band bands[IEEE80211_NUM_BANDS];
                                        ^
/opt/MT7630E-release/rt2x00/rt2x00.h:2167:22: error: field ‘curr_band’ has incomplete type
  enum ieee80211_band curr_band;
                      ^
/opt/MT7630E-release/rt2x00/rt2x00dev.c: In function ‘rt2x00lib_channel’:
/opt/MT7630E-release/rt2x00/rt2x00dev.c:945:32: error: ‘IEEE80211_BAND_2GHZ’ undeclared (first use in this function)
  entry->band = channel <= 14 ? IEEE80211_BAND_2GHZ : IEEE80211_BAND_5GHZ;
                                ^
/opt/MT7630E-release/rt2x00/rt2x00dev.c:945:32: note: each undeclared identifier is reported only once for each function it appears in
/opt/MT7630E-release/rt2x00/rt2x00dev.c:945:54: error: ‘IEEE80211_BAND_5GHZ’ undeclared (first use in this function)
  entry->band = channel <= 14 ? IEEE80211_BAND_2GHZ : IEEE80211_BAND_5GHZ;
                                                      ^
/opt/MT7630E-release/rt2x00/rt2x00dev.c: In function ‘rt2x00lib_probe_hw_modes’:
/opt/MT7630E-release/rt2x00/rt2x00dev.c:1009:20: error: ‘IEEE80211_BAND_2GHZ’ undeclared (first use in this function)
   rt2x00dev->bands[IEEE80211_BAND_2GHZ].n_channels = 14;
                    ^
/opt/MT7630E-release/rt2x00/rt2x00dev.c:1025:20: error: ‘IEEE80211_BAND_5GHZ’ undeclared (first use in this function)
   rt2x00dev->bands[IEEE80211_BAND_5GHZ].n_channels =
                    ^
In file included from ./include/linux/linkage.h:4:0,
                 from ./include/linux/kernel.h:6,
                 from /opt/MT7630E-release/rt2x00/rt2x00dev.c:27:
/opt/MT7630E-release/rt2x00/rt2x00dev.c: In function ‘rt2x00lib_remove_hw’:
/opt/MT7630E-release/rt2x00/rt2x00dev.c:1050:41: error: ‘IEEE80211_BAND_2GHZ’ undeclared (first use in this function)
  if (likely(rt2x00dev->hw->wiphy->bands[IEEE80211_BAND_2GHZ])) {
                                         ^
./include/linux/compiler.h:167:40: note: in definition of macro ‘likely’
 # define likely(x) __builtin_expect(!!(x), 1)
                                        ^
/opt/MT7630E-release/rt2x00/rt2x00dev.c:1054:31: error: ‘IEEE80211_BAND_5GHZ’ undeclared (first use in this function)
   rt2x00dev->hw->wiphy->bands[IEEE80211_BAND_5GHZ] = NULL;
                               ^
scripts/Makefile.build:289: recipe for target '/opt/MT7630E-release/rt2x00/rt2x00dev.o' failed
make[2]: **\* [/opt/MT7630E-release/rt2x00/rt2x00dev.o] Error 1
Makefile:1477: recipe for target '_module_/opt/MT7630E-release/rt2x00' failed
make[1]: **\* [_module_/opt/MT7630E-release/rt2x00] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-040800rc3-generic'
Makefile:8: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by glats** [comment]
Hi,  you must install the linux headers of your distro

**Comment by dcialdella** [comment]
I installed them.

**Comment by dcialdella** [comment]
apt-get install linux-headers-4.6.7-040607
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-4.6.7-040607 is already the newest version (4.6.7-040607.201608160432).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by dcialdella** [comment]
I will try t install and test it again.

**Comment by neurobin** [comment]
The repo is updated. Try the new one from [release branch](https://github.com/neurobin/MT7630E/tree/release) or [branch 2.0.7](https://github.com/neurobin/MT7630E/tree/2.0.7)

Note: You seem to have the headers installed. No need to reinstall.

**Comment by dcialdella** [comment]
I update to the last Firmware 

Linux **dac-TP300LA 4.8.0-040800rc4-generic** #201608312129 SMP Thu Sep 1 01:31:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

and then install the drivers, and It worked PERFECTLY !!!!! 

# **./install**

make -C /lib/modules/`uname -r`/build M=/home/dac/Downloads/MT7630E-release/rt2x00 modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-040800rc4-generic'
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00dev.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00mac.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00config.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00queue.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00link.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/mt_linux.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00crypto.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00firmware.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00leds.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00mmio.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2800pci.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2800lib.o
  CC [M]  /home/dac/Downloads/MT7630E-release/rt2x00/rt2x00pci.o
  LD [M]  /home/dac/Downloads/MT7630E-release/rt2x00/mt7630e.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/dac/Downloads/MT7630E-release/rt2x00/mt7630e.mod.o
  LD [M]  /home/dac/Downloads/MT7630E-release/rt2x00/mt7630e.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-040800rc4-generic'
make -C /lib/modules/`uname -r`/build M=/home/dac/Downloads/MT7630E-release/btloader modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-040800rc4-generic'
  CC [M]  /home/dac/Downloads/MT7630E-release/btloader/mt76xx.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/dac/Downloads/MT7630E-release/btloader/mt76xx.mod.o
  LD [M]  /home/dac/Downloads/MT7630E-release/btloader/mt76xx.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-040800rc4-generic'
cp -v firmware/_/_ /lib/firmware/
'firmware/BT/mt76x0.bin' -> '/lib/firmware/mt76x0.bin'
'firmware/Wi-FI/MT7650E234.bin' -> '/lib/firmware/MT7650E234.bin'
cp rt2x00/mt7630e.ko /lib/modules/`uname -r`/kernel/drivers/net/wireless/
cp btloader/mt76xx.ko /lib/modules/`uname -r`/kernel/drivers/net/wireless/
depmod

The driver has been successfully installed.
If you don't have wifi yet, try to reboot.
If bluetooth doesn't work, read the bluetooth
section in README.md file and follow through.

SOLVED NOW !!!!
thank you very much.

dac

**Comment by andreyshade** [comment]
I have problem with compile:

```
make -C /lib/modules/`uname -r`/build M=/home/andreyshade/MT7630E/rt2x00 modules
make[1]: Entering directory '/usr/src/linux-headers-4.8.0-11-generic'
  CC [M]  /home/andreyshade/MT7630E/rt2x00/rt2800pci.o
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1704:8: error: type defaults to ‘int’ in declaration of ‘DEFINE_PCI_DEVICE_TABLE’ [-Werror=implicit-int]
 static DEFINE_PCI_DEVICE_TABLE(rt2800pci_device_table) = {
        ^~~~~~~~~~~~~~~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1704:1: warning: parameter names (without types) in function declaration
 static DEFINE_PCI_DEVICE_TABLE(rt2800pci_device_table) = {
 ^~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1704:1: error: function ‘DEFINE_PCI_DEVICE_TABLE’ is initialized like a variable
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:2: warning: braces around scalar initializer
  { PCI_DEVICE(0x14c3, 0x7630) },
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
In file included from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:39:0:
./include/linux/pci.h:695:2: error: field name not in record or union initializer
  .vendor = (vend), .device = (dev), \
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:695:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:695:12: error: invalid initializer
  .vendor = (vend), .device = (dev), \
            ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:695:12: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
            ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:695:20: error: field name not in record or union initializer
  .vendor = (vend), .device = (dev), \
                    ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:695:20: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
                    ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:695:30: warning: excess elements in scalar initializer
  .vendor = (vend), .device = (dev), \
                              ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:695:30: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
                              ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:696:2: error: field name not in record or union initializer
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:696:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
In file included from ./include/linux/of.h:22:0,
                 from ./include/net/dsa.h:18,
                 from ./include/linux/netdevice.h:44,
                 from ./include/linux/etherdevice.h:26,
                 from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:35:
./include/linux/mod_devicetable.h:16:20: warning: excess elements in scalar initializer
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:15: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
               ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/mod_devicetable.h:16:20: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:15: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
               ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
In file included from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:39:0:
./include/linux/pci.h:696:27: error: field name not in record or union initializer
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                           ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/pci.h:696:27: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                           ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
In file included from ./include/linux/of.h:22:0,
                 from ./include/net/dsa.h:18,
                 from ./include/linux/netdevice.h:44,
                 from ./include/linux/etherdevice.h:26,
                 from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:35:
./include/linux/mod_devicetable.h:16:20: warning: excess elements in scalar initializer
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:40: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                                        ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
./include/linux/mod_devicetable.h:16:20: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:40: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                                        ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1705:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7630) },
    ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:2: warning: braces around scalar initializer
  { PCI_DEVICE(0x14c3, 0x7650) },
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
In file included from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:39:0:
./include/linux/pci.h:695:2: error: field name not in record or union initializer
  .vendor = (vend), .device = (dev), \
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:695:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:695:12: error: invalid initializer
  .vendor = (vend), .device = (dev), \
            ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:695:12: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
            ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:695:20: error: field name not in record or union initializer
  .vendor = (vend), .device = (dev), \
                    ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:695:20: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
                    ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:695:30: warning: excess elements in scalar initializer
  .vendor = (vend), .device = (dev), \
                              ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:695:30: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .vendor = (vend), .device = (dev), \
                              ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:696:2: error: field name not in record or union initializer
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:696:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
In file included from ./include/linux/of.h:22:0,
                 from ./include/net/dsa.h:18,
                 from ./include/linux/netdevice.h:44,
                 from ./include/linux/etherdevice.h:26,
                 from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:35:
./include/linux/mod_devicetable.h:16:20: warning: excess elements in scalar initializer
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:15: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
               ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/mod_devicetable.h:16:20: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:15: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
               ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
In file included from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:39:0:
./include/linux/pci.h:696:27: error: field name not in record or union initializer
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                           ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/pci.h:696:27: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                           ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
In file included from ./include/linux/of.h:22:0,
                 from ./include/net/dsa.h:18,
                 from ./include/linux/netdevice.h:44,
                 from ./include/linux/etherdevice.h:26,
                 from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:35:
./include/linux/mod_devicetable.h:16:20: warning: excess elements in scalar initializer
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:40: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                                        ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
./include/linux/mod_devicetable.h:16:20: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
 #define PCI_ANY_ID (~0)
                    ^
./include/linux/pci.h:696:40: note: in expansion of macro ‘PCI_ANY_ID’
  .subvendor = PCI_ANY_ID, .subdevice = PCI_ANY_ID
                                        ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:4: note: in expansion of macro ‘PCI_DEVICE’
  { PCI_DEVICE(0x14c3, 0x7650) },
    ^~~~~~~~~~
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:2: warning: excess elements in scalar initializer
  { PCI_DEVICE(0x14c3, 0x7650) },
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1706:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1707:2: warning: braces around scalar initializer
  { 0, }
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1707:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1707:4: error: invalid initializer
  { 0, }
    ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1707:4: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1707:2: warning: excess elements in scalar initializer
  { 0, }
  ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1707:2: note: (near initialization for ‘DEFINE_PCI_DEVICE_TABLE’)
In file included from ./include/linux/phy.h:24:0,
                 from ./include/net/dsa.h:19,
                 from ./include/linux/netdevice.h:44,
                 from ./include/linux/etherdevice.h:26,
                 from /home/andreyshade/MT7630E/rt2x00/rt2800pci.c:35:
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1717:26: error: ‘rt2800pci_device_table’ undeclared here (not in a function)
 MODULE_DEVICE_TABLE(pci, rt2800pci_device_table);
                          ^
./include/linux/module.h:213:21: note: in definition of macro ‘MODULE_DEVICE_TABLE’
 extern const typeof(name) __mod_##type##__##name##_device_table  \
                     ^~~~
./include/linux/module.h:213:27: error: ‘__mod_pci__rt2800pci_device_table_device_table’ aliased to undefined symbol ‘rt2800pci_device_table’
 extern const typeof(name) __mod_##type##__##name##_device_table  \
                           ^
/home/andreyshade/MT7630E/rt2x00/rt2800pci.c:1717:1: note: in expansion of macro ‘MODULE_DEVICE_TABLE’
 MODULE_DEVICE_TABLE(pci, rt2800pci_device_table);
 ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:289: recipe for target '/home/andreyshade/MT7630E/rt2x00/rt2800pci.o' failed
make[2]: *** [/home/andreyshade/MT7630E/rt2x00/rt2800pci.o] Error 1
Makefile:1489: recipe for target '_module_/home/andreyshade/MT7630E/rt2x00' failed
make[1]: *** [_module_/home/andreyshade/MT7630E/rt2x00] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.8.0-11-generic'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by glats** [comment]
@andreyshade which distro? 
pls add more details

**Comment by glats** [comment]
@andreyshade try to install build-essential package and clone or checkout the last commit

**Comment by andreyshade** [comment]
@glats I have tried to build on latest commit. How to install build-essential package?

**Comment by glats** [comment]
@andreyshade sudo apt-get install build-essential
also add more details

**Comment by andreyshade** [comment]
```
/home/andreyshade/MT7630E# sudo apt-get install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

./install return the same result. What additional details needed?

**Comment by dcialdella** [comment]
I think the error is related to the version of kernel. I could compile it with some versions, and NOT with other versions.... not sure exactly the kind of error.
(Suggestion, try a new kernel)

**Comment by neurobin** [comment]
@dcialdella : forgot to mention, this problem is fixed in 2.0.8. issue #42

**Comment by yayapipi** [comment]
https://github.com/neurobin/MT7630E/tree/2.0.7
this work in Tp500ln
